repos:
  - repo: local
    hooks:
      # Run the formatter first
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
      # Then run the linter
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]