[project]
name = "lazy-ecs"
version = "0.1.0"
description = "A CLI tool for working with AWS services"
readme = "README.md"
authors = [
    { name = "Janne Sinivirta", email = "janne.sinivirta@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "questionary>=2.0.0",
    "boto3>=1.34.0",
    "rich>=13.0.0",
]

[project.scripts]
lazy-ecs = "lazy_ecs:main"

[tool.uv]
dev-dependencies = [
    "pytest>=8.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.12.0",
    "moto[ecs]>=5.0.0",
    "ruff>=0.6.0",
    "pre-commit>=4.0.0",
    "pyrefly>=0.1.0",
    "boto3-stubs[ecs]>=1.34.0",
]

[tool.ruff]
target-version = "py311"
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = []

[tool.pyrefly]
project-includes = ["**/*"]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/*venv/**/*",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--cov=src/lazy_ecs",
    "--cov-report=term-missing",
    "--cov-report=html",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
